// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFoY59ejw5fHel42jDDyZnpst2wirfS0',
    appId: '1:14105920861:web:c3782fad6075f35ad354b4',
    messagingSenderId: '14105920861',
    projectId: 'pharmacy-pos-system',
    authDomain: 'pharmacy-pos-system.firebaseapp.com',
    storageBucket: 'pharmacy-pos-system.appspot.com',
    measurementId: 'G-QG29ZZ1EN8',
    databaseURL: 'https://pharmacy-pos-system-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBz70ncaTnubMeh4pBzimm4G_9OeI7xN8',
    appId: '1:14105920861:android:df0102de0cb036bed354b4',
    messagingSenderId: '14105920861',
    projectId: 'pharmacy-pos-system',
    storageBucket: 'pharmacy-pos-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWi5Z2ZWC6fuyAVHAiwr6SYmdfojKggQU',
    appId: '1:14105920861:ios:a20a698ea11efaddd354b4',
    messagingSenderId: '14105920861',
    projectId: 'pharmacy-pos-system',
    storageBucket: 'pharmacy-pos-system.appspot.com',
    iosBundleId: 'com.example.pharmacyPosSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWi5Z2ZWC6fuyAVHAiwr6SYmdfojKggQU',
    appId: '1:14105920861:ios:a20a698ea11efaddd354b4',
    messagingSenderId: '14105920861',
    projectId: 'pharmacy-pos-system',
    storageBucket: 'pharmacy-pos-system.appspot.com',
    iosBundleId: 'com.example.pharmacyPosSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFoY59ejw5fHel42jDDyZnpst2wirfS0',
    appId: '1:14105920861:web:e952ea0daf600c91d354b4',
    messagingSenderId: '14105920861',
    projectId: 'pharmacy-pos-system',
    authDomain: 'pharmacy-pos-system.firebaseapp.com',
    storageBucket: 'pharmacy-pos-system.appspot.com',
    measurementId: 'G-S68RV1N9S1',
    databaseURL: 'https://pharmacy-pos-system-default-rtdb.firebaseio.com/'
  );
}
